language: node_js

node_js:
  - "stable"
  - "lts/*"

os:
  - linux
  - osx

cache: yarn

before_install: yarn global add greenkeeper-lockfile@latest

before_script: greenkeeper-lockfile-update

after_script: greenkeeper-lockfile-upload

after_success: npm run coveralls