environment:
  matrix:
    - nodejs_version: "Current"
    - nodejs_version: "LTS"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

test_script:
  - node --version
  - npm --version
  - npm test

build: off